name: 更新二进制可执行文件

on:
  workflow_dispatch:
  push:
    paths:
      - language.cpp

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 安装GCC对ARM交叉编译工具链
        run: sudo apt install g++-aarch64-linux-gnu
        
      - name: 编译源代码
        run: |
            g++ -o language --static -std=c++20 language.cpp
            aarch64-linux-gnu-g++ -o language_arm --static -std=c++20 language.cpp

      - uses: actions/upload-artifact@v4
        with: 
          name: 可执行二进制文件
          path: |
            language_arm
            language

  push:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: 可执行二进制文件

      - name: 提交
        run: |
              git config --global user.email "gaojian520one@outlook.com"
              git config --global user.name "TheWhiteDog9487"
              git add .
              git commit -m "新的二进制文件"
              git push

      - name: 推送
        uses: ad-m/github-push-action@master