name: 更新二进制可执行文件

on:
    push:
        paths:
            - language.cpp

jobs:
    build:
        permissions:
            contents: write
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: 安装GCC对ARM交叉编译工具链
              run: apt install gcc-arm-none-eabi
            
            - name: 编译源代码
              run: |
                arm-none-eabi-g++ -o language_arm --static language.cpp
                g++ -o language --static language.cpp

            - name: 提交
              run: |
                git config --global user.email "gaojian520one@outlook.com"
                git config --global user.name "TheWhiteDog9487"
                git add .
                git commit -m "新的二进制文件"
                git push

            - name: 推送
              uses: ad-m/github-push-action@master